### ISSUE TITLE
Provide favicon

### ISSUE THREAD

**Issue by Macxim** [Federfleisch/federfleisch.github.io#1]

**Comment by Federfleisch** [comment]
BULLSHIT DU CONCRET BORDAYL

**Comment by Federfleisch** [comment]
Is 32x32 ok?

![favicon](https://cloud.githubusercontent.com/assets/14271051/9909457/9b009ac0-5c98-11e5-95d3-60e261c3cd5c.png)

**Comment by Macxim** [comment]
That should do it. :+1:

**Comment by Macxim** [comment]
https://github.com/Federfleisch/federfleisch.github.io/pull/4
