### ISSUE TITLE
Add og:img for Facebook sharing

### ISSUE THREAD

**Issue by Macxim** [Federfleisch/federfleisch.github.io#10]

**Comment by Macxim** [comment]
The image appears to be too large: 
https://developers.facebook.com/docs/sharing/best-practices#images

**Comment by Federfleisch** [comment]
![og](https://cloud.githubusercontent.com/assets/14271051/11028886/0304f68a-86c3-11e5-822b-6bb1e1e2b330.png)

**Comment by Macxim** [comment]
C'est normal la bordure moche à gauche ?

**Comment by Federfleisch** [comment]
![og](https://cloud.githubusercontent.com/assets/14271051/11028920/5bbfc5b6-86c3-11e5-9244-8ba4fa1040d6.jpg)

**Comment by Macxim** [comment]
Home is OK but inner pages aren't.
https://developers.facebook.com/tools/debug/og/object/
`Error parsing input URL, no data was cached, or no data was scraped.`

**Comment by Macxim** [comment]
http://www.bebetterdeveloper.com/deployment/sharing-a-blog-post-hosted-on-github-pages.html
This seems to fix it.
